#!/usr/bin/env fish

if test -e .venv
    echo 'Project is already linked to a virtual env, please see .venv file'
else
    set env_name $argv[1]
    touch .venv
    echo $env_name > .venv 
    vf new $env_name
end
