#!/usr/bin/env fish

if test -e .vf
    echo 'Project is already linked to a virtual env, please see .vf file'
else
    set env_name $argv[1]
    touch .vf
    echo $env_name > .vf 
    vf new $env_name
end
